name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv requirements --dev > requirements.txt
          pip uninstall pipenv -y
          pip install -r requirements.txt

      - name: Configure environment variables

        run: |
          cp .env.example .env

      - name: Test coverage
        run: |
          coverage run -m pytest -v
          coverage report -m

      - name: Pylint test
        run: |
          pylint --extension-pkg-whitelist="pydantic" app

      - name: Running Docker build
        env:
          DOCKER_BUILDKIT: 1
        run: docker build .
